Port.create(:code=>'LV888', :name=>'Latvia (GENERIC)', :country=>'Latvia', :longitude=>"(N)56° 57' 0''", :latitude=>"(E)24°  6' 0''")
Port.create(:code=>'LVAIN', :name=>'Ainazi', :country=>'Latvia', :longitude=>"(N)54° 52' 0''", :latitude=>"(E)24°  21' 0''")
Port.create(:code=>'LVAIZ', :name=>'Aizkraukle', :country=>'Latvia', :longitude=>"(N)56° 36' 0''", :latitude=>"(E)25°  13' 0''")
Port.create(:code=>'LVBMT', :name=>'Baltmarine Terminal, Riga', :country=>'Latvia', :longitude=>"", :latitude=>"")
Port.create(:code=>'LVJPS', :name=>'Jekabpils', :country=>'Latvia', :longitude=>"(N)56° 29' 0''", :latitude=>"(E)25°  51' 0''")
Port.create(:code=>'LVLMS', :name=>'Lapmezciems', :country=>'Latvia', :longitude=>"(N)57° 0' 0''", :latitude=>"(E)23°  31' 0''")
Port.create(:code=>'LVLPX', :name=>'Liepaja', :country=>'Latvia', :longitude=>"(N)56° 31' 0''", :latitude=>"(E)21°  1' 0''")
Port.create(:code=>'LVMRX', :name=>'Mersrags', :country=>'Latvia', :longitude=>"(N)57° 20' 0''", :latitude=>"(E)23°  6' 0''")
Port.create(:code=>'LVORE', :name=>'Ogre', :country=>'Latvia', :longitude=>"(N)56° 48' 0''", :latitude=>"(E)24°  37' 0''")
Port.create(:code=>'LVRIX', :name=>'Riga', :country=>'Latvia', :longitude=>"", :latitude=>"")
Port.create(:code=>'LVROJ', :name=>'Roja', :country=>'Latvia', :longitude=>"(N)57° 30' 0''", :latitude=>"(E)22°  48' 0''")
Port.create(:code=>'LVSAL', :name=>'Salacgriva', :country=>'Latvia', :longitude=>"(N)57° 45' 0''", :latitude=>"(E)24°  21' 0''")
Port.create(:code=>'LVSKU', :name=>'Skulte', :country=>'Latvia', :longitude=>"(N)57° 19' 0''", :latitude=>"(E)24°  26' 0''")
Port.create(:code=>'LVVNT', :name=>'Ventspils', :country=>'Latvia', :longitude=>"", :latitude=>"")
